{% set name = "manhole" %}
{% set version = "1.7.0" %}
{% set sha256 = "224985bf1dd032f2dc0ca4107f727835b6f50e1df6d78781d6c9f4cae8b585e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - manhole-cli = manhole.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - manhole
  commands:
    - manhole-cli --help

about:
  home: https://github.com/ionelmc/python-manhole
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Debugging manhole for python applications
