{% set name = "manhole" %}
{% set version = "1.6.0" %}
{% set sha256 = "d4ab98198481ed54a5b95c0439f41131f56d7d3755eedaedce5a45ca7ff4aa42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
    - manhole-cli = manhole.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - manhole
  commands:
    - manhole-cli --help

about:
  home: https://github.com/ionelmc/python-manhole
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Debugging manhole for python applications
